// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRG.Infrastructure.Persistence;

#nullable disable

namespace SRG.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603144909_AddRateGroups")]
    partial class AddRateGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRG.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityName");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FamilyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubFamilyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("FamilyCode", "SubFamilyCode");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("Crews", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.CrewAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("UserId");

                    b.HasIndex("CrewId", "UserId")
                        .IsUnique();

                    b.ToTable("CrewAccessList", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SubcontractorCrewId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CrewId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubcontractorCrewId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("Date", "CrewId")
                        .IsUnique()
                        .HasFilter("\"CrewId\" IS NOT NULL");

                    b.HasIndex("Date", "SubcontractorCrewId")
                        .IsUnique()
                        .HasFilter("\"SubcontractorCrewId\" IS NOT NULL");

                    b.ToTable("DailyReports", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByWorkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("DailyReportId", "EntryId");

                    b.ToTable("DailyReportChangeHistory");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author_email");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("author_role");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_report_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<int>("Section")
                        .HasColumnType("integer")
                        .HasColumnName("section");

                    b.Property<Guid?>("SubcontractorWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcontractor_worker_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("SubcontractorWorkerId");

                    b.ToTable("daily_report_comments", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedByEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("changed_by_email");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid?>("ChangedByWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_worker_id");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_report_id");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ChangedByWorkerId");

                    b.HasIndex("DailyReportId");

                    b.ToTable("daily_report_status_history", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportWorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("DailyReportId", "WorkOrderId")
                        .IsUnique();

                    b.ToTable("DailyReportWorkOrders", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.GoodsReceivedVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("GoodsReceivedVouchers", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.GoodsReceivedVoucherItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ExtendedPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("GoodsReceivedVoucherId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("VendorPartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceivedVoucherId");

                    b.HasIndex("MaterialId");

                    b.ToTable("GoodsReceivedVoucherItems", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.InewiIntegrationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ConfiguredById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredById");

                    b.HasIndex("SubcontractorId")
                        .IsUnique();

                    b.ToTable("InewiIntegrationSettings", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.InewiRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Hours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportedById")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedById");

                    b.HasIndex("SubcontractorId", "Date", "WorkerName")
                        .IsUnique();

                    b.ToTable("InewiRecords", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceivedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReceivedBySubcontractorWorkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReceivedByWorkerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ToWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ReceivedBySubcontractorWorkerId");

                    b.HasIndex("ReceivedByWorkerId");

                    b.HasIndex("ToWarehouseId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.IssueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("MaterialId");

                    b.ToTable("IssueItems", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.MaterialRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByWorkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByWorkerId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("MaterialRequests");
                });

            modelBuilder.Entity("SRG.Domain.Entities.MaterialUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderedMaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderedMaterialId");

                    b.ToTable("MaterialUsages", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.OrderedMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddedById")
                        .HasColumnType("uuid");

                    b.Property<string>("AddedByRole")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("OrderedMaterials", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.OrderedWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("SectionId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("OrderedWorks", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.ProjectSubcontractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubcontractorId");

                    b.HasIndex("ProjectId", "SubcontractorId")
                        .IsUnique();

                    b.ToTable("ProjectSubcontractors", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.RateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubcontractorId");

                    b.ToTable("RateGroups");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Return", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ToWarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ToWarehouseId");

                    b.ToTable("Returns", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.ReturnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnItems", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("QuantityAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityBefore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("WarehouseId", "CreatedAt");

                    b.ToTable("StockMovements", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorCrew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentForemanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentForemanId");

                    b.HasIndex("SubcontractorId");

                    b.ToTable("SubcontractorCrews", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorCrewPmAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedBySubcontractorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PmUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedBySubcontractorId");

                    b.HasIndex("PmUserId");

                    b.HasIndex("CrewId", "PmUserId")
                        .IsUnique();

                    b.ToTable("SubcontractorCrewPmAccessList");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorForemanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ForemanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ForemanId");

                    b.HasIndex("CrewId", "EndDate")
                        .IsUnique()
                        .HasFilter("\"EndDate\" IS NULL");

                    b.ToTable("SubcontractorForemanHistory", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultPassword")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InewiEmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("RateGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("RateGroupId");

                    b.HasIndex("SubcontractorId");

                    b.ToTable("SubcontractorWorkers", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMicrosoftLinked")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MicrosoftSubjectId")
                        .HasColumnType("text");

                    b.Property<string>("OneTimeLoginToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OneTimeLoginTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasFilter("\"Type\" = 'Main'");

                    b.HasIndex("Type", "OwnerId")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NOT NULL AND \"Type\" = 'Sub'");

                    b.ToTable("Warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Warehouse glowny",
                            Type = "Main"
                        });
                });

            modelBuilder.Entity("SRG.Domain.Entities.WarehouseStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WarehouseId", "MaterialId")
                        .IsUnique();

                    b.ToTable("WarehouseStocks", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("HoursSpent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsAddedByForeman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("OrderedWorkId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("OrderedWorkId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("WorkEntries", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyReportId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Hours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubcontractorWorkerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("SubcontractorWorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkHours", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkHours_ExactlyOneWorker", "(\"WorkerId\" IS NOT NULL AND \"SubcontractorWorkerId\" IS NULL) OR (\"WorkerId\" IS NULL AND \"SubcontractorWorkerId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DocumentationUrl")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly?>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlannedStartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SubcontractorCrewId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CrewId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubcontractorCrewId");

                    b.HasIndex("SubcontractorId");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("szt");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkTypes", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CrewId");

                    b.HasIndex("TeamId");

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("SRG.Domain.Entities.Category", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Crew", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Project", "Project")
                        .WithMany("Crews")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRG.Domain.Entities.CrewAccess", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Crew", "Crew")
                        .WithMany("AccessList")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Crew");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReport", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.Crew", "Crew")
                        .WithMany("DailyReports")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.Project", "Project")
                        .WithMany("DailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.Section", "Section")
                        .WithMany("DailyReports")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.SubcontractorCrew", "SubcontractorCrew")
                        .WithMany("DailyReports")
                        .HasForeignKey("SubcontractorCrewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("DailyReports")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Crew");

                    b.Navigation("Project");

                    b.Navigation("Section");

                    b.Navigation("SubcontractorCrew");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportChangeHistory", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("ChangeHistory")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("DailyReport");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportComment", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("Comments")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.DailyReportComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "SubcontractorWorker")
                        .WithMany()
                        .HasForeignKey("SubcontractorWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("DailyReport");

                    b.Navigation("ParentComment");

                    b.Navigation("SubcontractorWorker");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportStatusHistory", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "ChangedByWorker")
                        .WithMany()
                        .HasForeignKey("ChangedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("StatusHistory")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("ChangedByWorker");

                    b.Navigation("DailyReport");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportWorkOrder", b =>
                {
                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("DailyReportWorkOrders")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("DailyReportWorkOrders")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyReport");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SRG.Domain.Entities.GoodsReceivedVoucher", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SRG.Domain.Entities.GoodsReceivedVoucherItem", b =>
                {
                    b.HasOne("SRG.Domain.Entities.GoodsReceivedVoucher", "GoodsReceivedVoucher")
                        .WithMany("Items")
                        .HasForeignKey("GoodsReceivedVoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceivedVoucher");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SRG.Domain.Entities.InewiIntegrationSettings", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "ConfiguredBy")
                        .WithMany()
                        .HasForeignKey("ConfiguredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithOne()
                        .HasForeignKey("SRG.Domain.Entities.InewiIntegrationSettings", "SubcontractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguredBy");

                    b.Navigation("Subcontractor");
                });

            modelBuilder.Entity("SRG.Domain.Entities.InewiRecord", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "ImportedBy")
                        .WithMany()
                        .HasForeignKey("ImportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedBy");

                    b.Navigation("Subcontractor");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Installation", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Section", "Section")
                        .WithMany("Installations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Issue", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Warehouse", "FromWarehouse")
                        .WithMany()
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "ReceivedBySubcontractorWorker")
                        .WithMany()
                        .HasForeignKey("ReceivedBySubcontractorWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.Worker", "ReceivedByWorker")
                        .WithMany()
                        .HasForeignKey("ReceivedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.Warehouse", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Issues")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("FromWarehouse");

                    b.Navigation("ReceivedBySubcontractorWorker");

                    b.Navigation("ReceivedByWorker");

                    b.Navigation("ToWarehouse");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SRG.Domain.Entities.IssueItem", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Issue", "Issue")
                        .WithMany("Items")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Material", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Category", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SRG.Domain.Entities.MaterialRequest", b =>
                {
                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId");

                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByWorker");

                    b.Navigation("Material");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SRG.Domain.Entities.MaterialUsage", b =>
                {
                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.OrderedMaterial", "OrderedMaterial")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("OrderedMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyReport");

                    b.Navigation("Material");

                    b.Navigation("OrderedMaterial");
                });

            modelBuilder.Entity("SRG.Domain.Entities.OrderedMaterial", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("OrderedMaterials")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Material");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SRG.Domain.Entities.OrderedWork", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("OrderedWorks")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.WorkType", "WorkType")
                        .WithMany("OrderedWorks")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");

                    b.Navigation("Section");

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Project", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SRG.Domain.Entities.ProjectSubcontractor", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Project", "Project")
                        .WithMany("ProjectSubcontractors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Subcontractor");
                });

            modelBuilder.Entity("SRG.Domain.Entities.RateGroup", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcontractor");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Return", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Warehouse", "FromWarehouse")
                        .WithMany()
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Warehouse", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("SRG.Domain.Entities.ReturnItem", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Return", "Return")
                        .WithMany("Items")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Section", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Project", "Project")
                        .WithMany("Sections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRG.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorCrew", b =>
                {
                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "CurrentForeman")
                        .WithMany()
                        .HasForeignKey("CurrentForemanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentForeman");

                    b.Navigation("Subcontractor");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorCrewPmAccess", b =>
                {
                    b.HasOne("SRG.Domain.Entities.SubcontractorCrew", "Crew")
                        .WithMany("PmAccessList")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.User", "GrantedBySubcontractor")
                        .WithMany()
                        .HasForeignKey("GrantedBySubcontractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.User", "PmUser")
                        .WithMany()
                        .HasForeignKey("PmUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("GrantedBySubcontractor");

                    b.Navigation("PmUser");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorForemanHistory", b =>
                {
                    b.HasOne("SRG.Domain.Entities.SubcontractorCrew", "Crew")
                        .WithMany("ForemanHistory")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "Foreman")
                        .WithMany("ForemanHistory")
                        .HasForeignKey("ForemanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Foreman");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorWorker", b =>
                {
                    b.HasOne("SRG.Domain.Entities.SubcontractorCrew", "Crew")
                        .WithMany("Workers")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.RateGroup", "RateGroup")
                        .WithMany("Workers")
                        .HasForeignKey("RateGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("RateGroup");

                    b.Navigation("Subcontractor");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Team", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Crew", "Crew")
                        .WithMany("Teams")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("SRG.Domain.Entities.WarehouseStock", b =>
                {
                    b.HasOne("SRG.Domain.Entities.Material", "Material")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkEntry", b =>
                {
                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("WorkEntries")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.OrderedWork", "OrderedWork")
                        .WithMany("WorkEntries")
                        .HasForeignKey("OrderedWorkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.WorkType", "WorkType")
                        .WithMany("WorkEntries")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyReport");

                    b.Navigation("OrderedWork");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkHour", b =>
                {
                    b.HasOne("SRG.Domain.Entities.DailyReport", "DailyReport")
                        .WithMany("WorkHours")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.SubcontractorWorker", "SubcontractorWorker")
                        .WithMany("WorkHours")
                        .HasForeignKey("SubcontractorWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkHour")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyReport");

                    b.Navigation("SubcontractorWorker");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Crew", "Crew")
                        .WithMany()
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SRG.Domain.Entities.SubcontractorCrew", "SubcontractorCrew")
                        .WithMany()
                        .HasForeignKey("SubcontractorCrewId");

                    b.HasOne("SRG.Domain.Entities.User", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Crew");

                    b.Navigation("Project");

                    b.Navigation("Section");

                    b.Navigation("Subcontractor");

                    b.Navigation("SubcontractorCrew");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Worker", b =>
                {
                    b.HasOne("SRG.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Crew", "Crew")
                        .WithMany("Worker")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRG.Domain.Entities.Team", "Team")
                        .WithMany("Worker")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Crew");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Category", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Crew", b =>
                {
                    b.Navigation("AccessList");

                    b.Navigation("DailyReports");

                    b.Navigation("Teams");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReport", b =>
                {
                    b.Navigation("ChangeHistory");

                    b.Navigation("Comments");

                    b.Navigation("DailyReportWorkOrders");

                    b.Navigation("MaterialUsages");

                    b.Navigation("StatusHistory");

                    b.Navigation("WorkEntries");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("SRG.Domain.Entities.DailyReportComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SRG.Domain.Entities.GoodsReceivedVoucher", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Material", b =>
                {
                    b.Navigation("WarehouseStocks");
                });

            modelBuilder.Entity("SRG.Domain.Entities.OrderedMaterial", b =>
                {
                    b.Navigation("MaterialUsages");
                });

            modelBuilder.Entity("SRG.Domain.Entities.OrderedWork", b =>
                {
                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Project", b =>
                {
                    b.Navigation("Crews");

                    b.Navigation("DailyReports");

                    b.Navigation("ProjectSubcontractors");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SRG.Domain.Entities.RateGroup", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Return", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Section", b =>
                {
                    b.Navigation("DailyReports");

                    b.Navigation("Installations");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorCrew", b =>
                {
                    b.Navigation("DailyReports");

                    b.Navigation("ForemanHistory");

                    b.Navigation("PmAccessList");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("SRG.Domain.Entities.SubcontractorWorker", b =>
                {
                    b.Navigation("ForemanHistory");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Team", b =>
                {
                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("WarehouseStocks");
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("DailyReportWorkOrders");

                    b.Navigation("DailyReports");

                    b.Navigation("Issues");

                    b.Navigation("OrderedMaterials");

                    b.Navigation("OrderedWorks");
                });

            modelBuilder.Entity("SRG.Domain.Entities.WorkType", b =>
                {
                    b.Navigation("OrderedWorks");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("SRG.Domain.Entities.Worker", b =>
                {
                    b.Navigation("WorkHour");
                });
#pragma warning restore 612, 618
        }
    }
}
